#!/usr/bin/env python3
# ══════════════════════════════════════════════════════════════════════════════
#  ytdl_host.py  –  Native Messaging Host  –  YT Downloader ✦
#
#  Protocolo Native Messaging de Chrome:
#    • Entrada:  stdin  → 4 bytes (longitud, little-endian) + JSON UTF-8
#    • Salida:   stdout → 4 bytes (longitud, little-endian) + JSON UTF-8
#
#  Comandos recibidos:
#    {"action": "ping"}
#    {"action": "download", "url":..., "format":..., "quality":..., "cookies":[...]}
#    {"action": "cancel"}
#
#  Mensajes enviados (streaming):
#    {"type": "pong",     "version": "1.0"}
#    {"type": "log",      "level": "ok|info|err|warn", "msg": "..."}
#    {"type": "title",    "title": "..."}
#    {"type": "progress", "pct": 50.0, "speed": "1.2 MiB/s", "eta": "00:30"}
#    {"type": "done",     "success": true/false, "error": "..."}
# ══════════════════════════════════════════════════════════════════════════════

import sys
import os
import json
import struct
import threading
import tempfile
import re
import traceback

HOST_VERSION = "1.0.0"

# ── Low-level Native Messaging I/O ──────────────────────────────────────────

def read_message():
    """Read one Native Messaging message from stdin."""
    raw_len = sys.stdin.buffer.read(4)
    if not raw_len or len(raw_len) < 4:
        return None
    msg_len = struct.unpack('<I', raw_len)[0]
    raw_msg = sys.stdin.buffer.read(msg_len)
    if not raw_msg:
        return None
    return json.loads(raw_msg.decode('utf-8'))


def send_message(obj):
    """Write one Native Messaging message to stdout."""
    data = json.dumps(obj, ensure_ascii=False).encode('utf-8')
    sys.stdout.buffer.write(struct.pack('<I', len(data)))
    sys.stdout.buffer.write(data)
    sys.stdout.buffer.flush()


# ── Helpers ──────────────────────────────────────────────────────────────────

def send_log(msg, level='info'):
    send_message({'type': 'log', 'level': level, 'msg': msg})


def send_progress(pct, speed='—', eta='—'):
    send_message({'type': 'progress', 'pct': pct, 'speed': speed, 'eta': eta})


def send_done(success, error=''):
    send_message({'type': 'done', 'success': success, 'error': error})


def strip_ansi(text):
    return re.sub(r'\x1b\[[0-9;]*m', '', text)


# ── Cookie file builder ──────────────────────────────────────────────────────

def build_cookie_file(cookie_lines):
    """
    Escribe las líneas en formato Netscape a un archivo temporal
    y devuelve la ruta. Debe borrarse después.
    """
    tf = tempfile.NamedTemporaryFile(
        mode='w', suffix='.txt', delete=False, encoding='utf-8'
    )
    tf.write('# Netscape HTTP Cookie File\n')
    tf.write('# Generated by YT Downloader ✦ Extension\n\n')
    for line in cookie_lines:
        tf.write(line + '\n')
    tf.close()
    return tf.name


# ── yt-dlp logger que redirige a Native Messaging ────────────────────────────

class NMLogger:
    def debug(self, msg):
        if msg.startswith('[debug]'):
            return
        clean = strip_ansi(msg).strip()
        if clean:
            send_log(clean, 'info')

    def info(self, msg):
        clean = strip_ansi(msg).strip()
        if clean:
            send_log(clean, 'info')

    def warning(self, msg):
        clean = strip_ansi(msg).strip()
        if clean:
            send_log(f'⚠ {clean}', 'warn')

    def error(self, msg):
        clean = strip_ansi(msg).strip()
        if clean:
            send_log(f'✘ {clean}', 'err')


# ── Format picker (misma lógica que v2.py) ───────────────────────────────────

def pick_format(formats, want, quality):
    if not formats:
        return 'best'

    if want == 'mp3':
        audio = [f for f in formats
                 if f.get('vcodec') in (None, 'none', '')
                 and f.get('acodec') not in (None, 'none', '')]
        if audio:
            try:
                best = max(audio, key=lambda f: f.get('abr') or 0)
                return best['format_id']
            except Exception:
                pass
        return 'bestaudio'

    video = [f for f in formats if f.get('vcodec') not in (None, 'none', '')]
    audio = [f for f in formats
             if f.get('vcodec') in (None, 'none', '')
             and f.get('acodec') not in (None, 'none', '')]

    if not video:
        return 'best'

    # Filter by requested quality (height)
    if quality and quality != 'best':
        try:
            max_h = int(quality)
            vid_q = [f for f in video if (f.get('height') or 0) <= max_h]
            if vid_q:
                video = vid_q
        except ValueError:
            pass

    try:
        ext = want  # 'mp4' or 'webm'
        vid_pref  = [f for f in video if f.get('ext') == ext]
        best_vid  = max(vid_pref or video,
                        key=lambda f: (f.get('height') or 0, f.get('tbr') or 0))

        if audio:
            aud_pref = (
                [f for f in audio if f.get('ext') in ('m4a', 'aac')] if ext == 'mp4'
                else [f for f in audio if f.get('ext') == 'webm']
            )
            best_aud = max(aud_pref or audio, key=lambda f: f.get('abr') or 0)
            return f"{best_vid['format_id']}+{best_aud['format_id']}"

        return best_vid['format_id']
    except Exception as e:
        send_log(f"⚠ Error al seleccionar formato: {e}, usando 'best' en su lugar", "warn")
        return 'best'


# ── Download logic ───────────────────────────────────────────────────────────

_cancel_event = threading.Event()


def progress_hook(d):
    if _cancel_event.is_set():
        raise Exception('Descarga cancelada por el usuario.')
    if d['status'] == 'downloading':
        raw   = d.get('_percent_str', '0%').strip()
        pct_s = strip_ansi(raw).replace('%', '').strip()
        try:
            pct = float(pct_s)
        except ValueError:
            pct = 0.0
        speed = strip_ansi(d.get('_speed_str', '—').strip())
        eta   = strip_ansi(d.get('_eta_str', '—').strip())
        send_progress(pct, speed, eta)
    elif d['status'] == 'finished':
        fname = os.path.basename(d.get('filename', ''))
        send_log(f'✔ Segmento guardado: {fname}', 'ok')
        send_progress(99, '—', '—')


def handle_download(msg):
    global _cancel_event
    _cancel_event.clear()

    url        = msg.get('url', '').strip()
    fmt        = msg.get('format', 'mp4')
    quality    = msg.get('quality', 'best')
    cookie_lines = msg.get('cookies', [])

    cookie_file = None

    try:
        import yt_dlp
    except ImportError as e:
        send_log(f'✘ Dependencia no instalada: {e}', 'err')
        send_done(False, f'Dependencia no encontrada: {e}')
        return

    # Write cookie file if we got cookies from the browser
    if cookie_lines:
        try:
            cookie_file = build_cookie_file(cookie_lines)
            send_log(f'🍪 Cookies escritas ({len(cookie_lines)} líneas)', 'ok')
        except Exception as e:
            send_log(f'⚠ No se pudo crear archivo de cookies: {e}', 'warn')
            cookie_file = None

    try:
        # ── Configurar yt-dlp para usar Node.js como JS interpreter ────────
        send_log('🔍 Obteniendo información del vídeo y descargando…', 'info')

        base_opts = {
            'quiet':       False,
            'no_warnings': False,
            'logger':      NMLogger(),
            'no_playlist': True,
            'http_headers': {
                'User-Agent': (
                    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                    'AppleWebKit/537.36 (KHTML, like Gecko) '
                    'Chrome/124.0.0.0 Safari/537.36'
                ),
            },
            'js_runtimes': {'node': {}},  # Usar Node.js como JS interpreter (formato correcto)
        }
        if cookie_file:
            base_opts['cookiefile'] = cookie_file

        # Seleccionar formato
        if fmt == 'mp3':
            format_str = 'bestaudio/best'
        else:
            format_str = 'bestvideo+bestaudio/best'
        
        out_dir  = os.path.join(os.path.expanduser('~'), 'Downloads')
        
        dl_opts  = {
            **base_opts,
            'format':          format_str,
            'outtmpl':         os.path.join(out_dir, '%(title)s.%(ext)s'),
            'progress_hooks':  [progress_hook],
        }
        if fmt == 'mp4':
            dl_opts['merge_output_format'] = 'mp4'
        elif fmt == 'mp3':
            dl_opts['postprocessors'] = [{
                'key':             'FFmpegExtractAudio',
                'preferredcodec':  'mp3',
                'preferredquality': '320',
            }]

        with yt_dlp.YoutubeDL(dl_opts) as ydl:
            ydl.download([url])

        send_log('✔ ¡Descarga completada!', 'ok')
        send_log(f'📂 Archivo guardado en: {out_dir}', 'info')
        send_done(True)

    except Exception as e:
        if _cancel_event.is_set():
            send_done(False, 'Descarga cancelada.')
            return
        full = traceback.format_exc()
        for line in full.splitlines():
            send_log(line, 'err')
        err_msg = str(e)
        if 'Sign in' in err_msg or 'bot' in err_msg.lower():
            err_msg = 'YouTube requiere autenticación. Inicia sesión en YouTube en Chrome.'
        elif 'ffmpeg' in err_msg.lower():
            err_msg = 'FFmpeg no encontrado. Instálalo: https://ffmpeg.org/download.html'
        send_done(False, err_msg)
    finally:
        if cookie_file and os.path.exists(cookie_file):
            try:
                os.remove(cookie_file)
            except Exception:
                pass


# ── Main loop ─────────────────────────────────────────────────────────────────

def main():
    # Redirect stderr so it doesn't corrupt the binary stdout protocol
    sys.stderr = open(os.devnull, 'w')

    while True:
        try:
            msg = read_message()
        except Exception:
            break

        if msg is None:
            break

        action = msg.get('action')

        if action == 'ping':
            send_message({'type': 'pong', 'version': HOST_VERSION})

        elif action == 'download':
            # Run in a thread so main loop stays responsive to cancel
            t = threading.Thread(target=handle_download, args=(msg,), daemon=True)
            t.start()
            t.join()  # block until done (one download at a time)

        elif action == 'cancel':
            _cancel_event.set()

        else:
            send_log(f'⚠ Acción desconocida: {action}', 'warn')


if __name__ == '__main__':
    main()
